package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nourhan
 */
public class book_cancal extends javax.swing.JFrame {
  Connection con;
  DefaultTableModel dtm;
   DefaultTableModel dtm1;
   DefaultTableModel dtm2;
    
    /**
     * Creates new form book_cancal
     */
    public book_cancal() {
      try {
          initComponents();
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic", "root", "قخخف");
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
      
      dtm = new DefaultTableModel();
      
      dtm.addColumn("Name");
      dtm.addColumn("Id");
      dtm.addColumn("Phone");
      dtm.addColumn("address");
      dtm.addColumn("age");
      dtm.addColumn("gender");
      dtm.addColumn("email");
      
      
      fillTablePatient();
      
      dtm1= new DefaultTableModel();
      dtm1.addColumn("Id");
      dtm1.addColumn("Date");
      dtm1.addColumn("Time");
      
      fillTableAppointment();
      
      dtm2 = new DefaultTableModel();
      
      dtm2.addColumn("id");
       dtm2.addColumn("Drugs");
        dtm2.addColumn("Chroinc_disease");
         dtm2.addColumn("Genetic_disease");
          dtm2.addColumn("Compliant");
      
      fillTableMedical();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        edt_age = new javax.swing.JTextField();
        edt_address = new javax.swing.JTextField();
        edt_name = new javax.swing.JTextField();
        edt_phone = new javax.swing.JTextField();
        back_btn3 = new javax.swing.JButton();
        updata3 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        edt_id = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        edt_email = new javax.swing.JTextField();
        edt_date = new javax.swing.JTextField();
        edt_time = new javax.swing.JTextField();
        edt_chronic = new javax.swing.JTextField();
        edt_compliant = new javax.swing.JTextField();
        edt_genetic = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_medical = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_patient = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbl_appointment = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        jLabel49 = new javax.swing.JLabel();
        edt_drugs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(230, 108, 79));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Id");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel36.setText("Name");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel37.setText("Address");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel38.setText("Phone Number");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel41.setText("Gender");

        edt_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edt_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_addressActionPerformed(evt);
            }
        });

        edt_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_nameActionPerformed(evt);
            }
        });

        edt_phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_phoneActionPerformed(evt);
            }
        });

        back_btn3.setBackground(new java.awt.Color(85, 165, 255));
        back_btn3.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        back_btn3.setText("BACK");
        back_btn3.setBorder(new javax.swing.border.MatteBorder(null));
        back_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn3ActionPerformed(evt);
            }
        });

        updata3.setBackground(new java.awt.Color(85, 165, 255));
        updata3.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        updata3.setText("UBDATE");
        updata3.setBorder(new javax.swing.border.MatteBorder(null));
        updata3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updata3ActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(85, 165, 255));
        btn_add.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btn_add.setText("add");
        btn_add.setBorder(new javax.swing.border.MatteBorder(null));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        edt_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_idActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel42.setText("Age");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel43.setText("complaint");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel44.setText("Gentic Disease");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel45.setText("Cronic Disease");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel46.setText("Time");

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel47.setText("Date");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel48.setText("Email");

        edt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_emailActionPerformed(evt);
            }
        });

        edt_date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_dateActionPerformed(evt);
            }
        });

        edt_time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_timeActionPerformed(evt);
            }
        });

        edt_chronic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_chronic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_chronicActionPerformed(evt);
            }
        });

        edt_compliant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edt_genetic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_medical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "cronic disease", "gentic disease", "drugs", "compliant"
            }
        ));
        tbl_medical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_medicalMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbl_medical);

        tbl_patient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tbl_patient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "name", "id", "phone", "address", "age", "gender", ""
            }
        ));
        tbl_patient.setSelectionForeground(new java.awt.Color(85, 165, 255));
        tbl_patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_patientMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tbl_patient);

        tbl_appointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "date", "time"
            }
        ));
        tbl_appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_appointmentMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tbl_appointment);

        btn_delete.setBackground(new java.awt.Color(85, 165, 255));
        btn_delete.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(204, 0, 0));
        btn_delete.setText("DELETE");
        btn_delete.setBorder(new javax.swing.border.MatteBorder(null));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        rbtn_male.setBackground(new java.awt.Color(230, 108, 79));
        buttonGroup1.add(rbtn_male);
        rbtn_male.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtn_male.setText("Male");

        rbtn_female.setBackground(new java.awt.Color(230, 108, 79));
        buttonGroup1.add(rbtn_female);
        rbtn_female.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtn_female.setText("Female");

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel49.setText("Drugs");

        edt_drugs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/66666666666666666.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(rbtn_male)
                                .addGap(77, 77, 77)
                                .addComponent(rbtn_female)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edt_drugs, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edt_genetic, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_chronic, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_compliant, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(back_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343)
                .addComponent(updata3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel40)
                    .addContainerGap(1696, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edt_chronic, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edt_genetic, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edt_compliant, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edt_drugs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(edt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtn_male, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtn_female, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updata3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(566, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(265, 265, 265)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void fillTablePatient(){
      try {
         
          dtm.setRowCount(0);
          PreparedStatement stmt = con.prepareStatement("select  name , p_id, phone , address , age ,gender ,email from patient");
          ResultSet rs= stmt.executeQuery();
          while (rs.next()){
             
              dtm.addRow(new Object[]{rs.getString(1),rs.getInt(2) ,rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6), rs.getString(7)});
             
          }
          tbl_patient.setModel(dtm);
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    
    private void fillTableAppointment(){
        
      try {
          dtm1.setRowCount(0);
          PreparedStatement stmt = con.prepareStatement("select  p_id, date,time from appointment");
          ResultSet rs =stmt.executeQuery();
          while (rs.next()){
             
              dtm1.addRow(new Object[]{rs.getInt(1),rs.getString(2) ,rs.getString(3)});
             
          }
          tbl_appointment.setModel(dtm1);
          
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
         
    }
    
    
    private void fillTableMedical(){
        
        
      try {
          dtm2.setRowCount(0);
          PreparedStatement stmt = con.prepareStatement("select p_id,drugs,chroinc_disease,genetic_disease,compliant from medical_history");
          ResultSet rs =stmt.executeQuery();
            while (rs.next()){
             
              dtm2.addRow(new Object[]{rs.getInt(1),rs.getString(2) ,rs.getString(3),rs.getString(4),rs.getString(5)});
             
          }
          tbl_medical.setModel(dtm2);
           
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
        
        
    }
    
    
    
    
    
    
    private void edt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_addressActionPerformed

    private void edt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_nameActionPerformed

    private void edt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_phoneActionPerformed

    private void back_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn3ActionPerformed
        // TODO add your handling code here:
        MenuPage show=new MenuPage();
        show.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_btn3ActionPerformed

    private void updata3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updata3ActionPerformed
        // TODO add your handling code here:
         
        try {
             int id = Integer.parseInt(edt_id.getText());
             String p_name = edt_name.getText();
             String phone = edt_phone.getText();
             String address= edt_address.getText();
             String age = edt_age.getText();
             String email = edt_email.getText();
             String gender ;
             if(rbtn_male.isSelected()){
                 gender = "Male";
             }else{
                 gender =" Female";
             }
             
          // TODO add your handling code here:
          PreparedStatement stmt = con.prepareStatement("update patient set name=? , phone=?  , address=?  , age=? , gender=?,email=? where p_id=?");
          stmt.setString(1, p_name);
          stmt.setString(2, phone);
          stmt.setString(3, address);
          stmt.setString(4, age);
          stmt.setString(5, gender);
          stmt.setString(6, email);
          stmt.setInt(7, id);
          
          
          stmt.executeUpdate(); 
          JOptionPane.showMessageDialog(this, "updated successfully");
          fillTablePatient();
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
        
        
        
              try {
        
       String date= edt_date.getText();
       String time= edt_time.getText();
       
       
       
          PreparedStatement stmt = con.prepareStatement("update appointment set date =?,time=? where p_id=?");
          
          
          
          stmt.setString(1, date);
          stmt.setString(2, time);
          
           stmt.executeUpdate(); 
          JOptionPane.showMessageDialog(this, "updated successfully");
          fillTableAppointment();
          
          
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
        
            
              
              
      try {
                     
       String drugs= edt_drugs.getText();
       String chronic= edt_chronic.getText();
        String genetic= edt_genetic.getText();
         String compliant= edt_compliant.getText();
         
            PreparedStatement stmt = con.prepareStatement("update medical_history set drugs=?,chroinc_disease=?,genetic_disease=?,compliant=? where p_id=?");
            
         
            stmt.setString(1, drugs);
            stmt.setString(2, chronic);
            stmt.setString(3, genetic);
            stmt.setString(4, compliant);
            
            
           stmt.executeUpdate(); 
          JOptionPane.showMessageDialog(this, "updated successfully");
          fillTableMedical(); 
            
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
         
         
       
        
        
    }//GEN-LAST:event_updata3ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
     
       
        try {
            
             int id = Integer.parseInt(edt_id.getText());
             String p_name = edt_name.getText();
             String phone = edt_phone.getText();
             String address= edt_address.getText();
             String age = edt_age.getText();
             String email = edt_email.getText();
             String gender ;
             if(rbtn_male.isSelected()){
                 gender = "Male";
             }else{
                 gender =" Female";
             }
            
            
          // TODO add your handling code here:
          PreparedStatement stmt = con.prepareStatement("insert into patient(name,phone,age,gender,email,address,p_id)values(?,?,?,?,?,?,?)");
          stmt.setString(1, p_name);
          stmt.setString(2, phone);
          stmt.setString(3, age);
          stmt.setString(4, gender);
          stmt.setString(5, email);
          stmt.setString(6, address);
          stmt.setInt(7, id);
          
          
          stmt.executeUpdate(); 
          JOptionPane.showMessageDialog(this, "Added successfully");
          fillTablePatient();
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
        
      
        
      try {
           int id = Integer.parseInt(edt_id.getText()); 
       String date= edt_date.getText();
       String time= edt_time.getText();
       
       
       
          PreparedStatement stmt = con.prepareStatement("insert into appointment(p_id,date,time)values(?,?,?)");
          
          
           stmt.setInt(1, id);
          stmt.setString(2, date);
          stmt.setString(3, time);
          
           stmt.executeUpdate(); 
          JOptionPane.showMessageDialog(this, "Added successfully");
          fillTableAppointment();
          
          
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
      
      
      
      
        
      try {
                int id = Integer.parseInt(edt_id.getText()); 
       String drugs= edt_drugs.getText();
       String chronic= edt_chronic.getText();
        String genetic= edt_genetic.getText();
         String compliant= edt_compliant.getText();
          
          
         PreparedStatement stmt   = con.prepareStatement("insert into medical_history(p_id,drugs,chroinc_disease,genetic_disease,compliant)values(?,?,?,?,?)");
         
         
            stmt.setInt(1, id);
            stmt.setString(2, drugs);
            stmt.setString(3, chronic);
            stmt.setString(4, genetic);
            stmt.setString(5, compliant);
            
            
                   stmt.executeUpdate(); 
          JOptionPane.showMessageDialog(this, "Added successfully");
          fillTableMedical();
            
            
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
          
          
         
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void edt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_idActionPerformed

    private void edt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_emailActionPerformed

    private void edt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_dateActionPerformed

    private void edt_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_timeActionPerformed

    private void edt_chronicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_chronicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_chronicActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
         try {    
       
      int id =Integer.parseInt( edt_id.getText());
          PreparedStatement stmt = con.prepareStatement("delete from patient where p_id=?");
          
          stmt.setInt(1, id);
           stmt.executeUpdate(); 
          JOptionPane.showMessageDialog(this, "deleted successfully");
          fillTablePatient();
          
          
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
         
      try {
           int id =Integer.parseInt( edt_id.getText());
          PreparedStatement stmt = con.prepareStatement("delete from appointment where p_id=?");
            stmt.setInt(1, id);
           stmt.executeUpdate(); 
          
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
      
      
         try {
           int id =Integer.parseInt( edt_id.getText());
          PreparedStatement stmt = con.prepareStatement("delete from medical_history where p_id=?");
            stmt.setInt(1, id);
           stmt.executeUpdate(); 
          
      } catch (SQLException ex) {
          Logger.getLogger(book_cancal.class.getName()).log(Level.SEVERE, null, ex);
      }
      
      
      
         
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_patientMouseClicked
        // TODO add your handling code here:
       edt_name.setText(tbl_patient.getValueAt(tbl_patient.getSelectedRow(), 0).toString()); 
       edt_id.setText(tbl_patient.getValueAt(tbl_patient.getSelectedRow(), 1).toString()); 
       edt_phone.setText(tbl_patient.getValueAt(tbl_patient.getSelectedRow(),2).toString());
       edt_address.setText(tbl_patient.getValueAt(tbl_patient.getSelectedRow(), 3).toString());
       edt_age.setText(tbl_patient.getValueAt(tbl_patient.getSelectedRow(), 4).toString());
       edt_email.setText(tbl_patient.getValueAt(tbl_patient.getSelectedRow(), 6).toString());
       
       
       if(tbl_patient.getValueAt(tbl_patient.getSelectedRow(), 5)!= null){
           if(tbl_patient.getValueAt(tbl_patient.getSelectedRow(),5).toString().equals("female"))
               

             rbtn_female.setSelected(true);
             else
             rbtn_male.setSelected(true);
       }
      
    }//GEN-LAST:event_tbl_patientMouseClicked

    private void tbl_appointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_appointmentMouseClicked
        // TODO add your handling code here:
        
          edt_id.setText(tbl_appointment.getValueAt(tbl_appointment.getSelectedRow(), 0).toString()); 
          edt_date.setText(tbl_appointment.getValueAt(tbl_appointment.getSelectedRow(), 1).toString());
          edt_time.setText(tbl_appointment.getValueAt(tbl_appointment.getSelectedRow(), 2).toString());
        
       
    }//GEN-LAST:event_tbl_appointmentMouseClicked

    private void tbl_medicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_medicalMouseClicked
        // TODO add your handling code here:
           edt_id.setText(tbl_medical.getValueAt(tbl_medical.getSelectedRow(), 0).toString());
           edt_drugs.setText(tbl_medical.getValueAt(tbl_medical.getSelectedRow(), 1).toString());
           edt_chronic.setText(tbl_medical.getValueAt(tbl_medical.getSelectedRow(), 2).toString());
           edt_genetic.setText(tbl_medical.getValueAt(tbl_medical.getSelectedRow(), 3).toString());
           edt_compliant.setText(tbl_medical.getValueAt(tbl_medical.getSelectedRow(), 4).toString());
          
    }//GEN-LAST:event_tbl_medicalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_cancal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_cancal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_cancal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_cancal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_cancal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn3;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edt_address;
    private javax.swing.JTextField edt_age;
    private javax.swing.JTextField edt_chronic;
    private javax.swing.JTextField edt_compliant;
    private javax.swing.JTextField edt_date;
    private javax.swing.JTextField edt_drugs;
    private javax.swing.JTextField edt_email;
    private javax.swing.JTextField edt_genetic;
    private javax.swing.JTextField edt_id;
    private javax.swing.JTextField edt_name;
    private javax.swing.JTextField edt_phone;
    private javax.swing.JTextField edt_time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTable tbl_appointment;
    private javax.swing.JTable tbl_medical;
    private javax.swing.JTable tbl_patient;
    private javax.swing.JButton updata3;
    // End of variables declaration//GEN-END:variables
}
